### ISSUE TITLE
thanks! incomplete last name for Matteo

### ISSUE THREAD

**Issue by yarikoptic** [Brainhack-Proceedings-2015/Halchenko_OHBM_DueCredit#1]
@ccraddock Thank you Cameron!  
@mvdoc your full last name is Visconti d O C... right? ;)  could you please send a PR fixing it up (look at PDF in top left corner) or @ccraddock is another procedure preferable for fixes?

**Comment by ccraddock** [comment]
Aye, you beat me to it! Please see my email. But you are the admin, handle
any way you like

-cc

On Tue, Feb 2, 2016 at 2:56 PM, Yaroslav Halchenko <notifications@github.com

> wrote:
> 
> @ccraddock https://github.com/ccraddock Thank you Cameron!
> 
> @mvdoc https://github.com/mvdoc your full last name is Visconti d O
> C... right? ;) could you please send a PR fixing it up (look at PDF in top
> left corner) or @ccraddock https://github.com/ccraddock is another
> procedure preferable for fixes?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Brainhack-Proceedings-2015/Halchenko_OHBM_DueCredit/issues/1
> .

## 

Director of Imaging, Center for the Developing Brain, Child Mind Institute
http://childmind.org
Director, Computational NeuroImaging Lab
http://computational-neuroimaging-lab.org/, Nathan S. Kline Institute for
Psychiatric Research http://www.rfmh.org/nki/
Co-Founder, The Neuro Bureau http://neurobureau.org
Impact Story https://impactstory.org/CameronCraddock
Google Scholar Citations
http://scholar.google.com/citations?user=lZ9hwSsAAAAJ&hl=en
GitHub https://github.com/ccraddock
Share that Brain @ the International Neuroimaging Datasharing Initiative
http://fcon_1000.projects.nitrc.org/!
Join me 2015-10-23 @ Brainhack Americas http://brainhack.org/Americas/!
The GigaScience Brainhack Thematic Series
http://brainhack.org/brainhack-thematic-series-call-for-papers/ is open
for your submission.

**Comment by mvdoc** [comment]
Thanks! see #2

**Comment by yarikoptic** [comment]
was closed by #2 and followup commit regenerating .tex and .pdf
