### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by dgmclare** [Brainhack-Proceedings-2015/Halchenko_OHBM_DueCredit#3]
I have no issues to report.

**Comment by mvdoc** [comment]
Thanks!

**Comment by lunebellec** [comment]
@mvdoc please close the issues that have been addressed. I'll consider the submission as accepted when all issues are closed. Thanks,

Pierre

**Comment by mvdoc** [comment]
Ok @pbellec . Thanks! Closing this issue.
