### ISSUE TITLE
Proceedings Review

### ISSUE THREAD

**Issue by nicholst** [Brainhack-Proceedings-2015/Halchenko_OHBM_DueCredit#4]
The work is well-motivated and concisely described.  Just a tiny bit more description, however, would be a great help to the reader...

It can be intuited what the _developer_ needs to do (add some calls to record the references that should be associated with the function).  But what does this look like to the user (be that the "end" user, or the 'developer' who is using DueCredit)?  Does each function called add to a 'stack' of citations, or is it really more of an bibliographic library for a tool developer?  Just a little more color as to how it would be used/embedded would make it easier for the reader to know how DueCredit will work.

**Comment by mvdoc** [comment]
Thanks for your comments @nicholst , we're addressing them.

**Comment by yarikoptic** [comment]
#5 and few subsequent changes addressed it a bit.  Could you please have a 2nd look at current state @nicholst ? (2cadf4896f5eb43ca7954fc594a915df685aa77e)  Thanks in advance

**Comment by nicholst** [comment]
Thanks, this is much clearer now.  

Only thing I wondered about was the 

> duecredit summary --format bibtex

command... where does that go?  At the end of the script?

**Comment by mvdoc** [comment]
We added a better description and an example of that command in #6 . Thanks @nicholst

**Comment by mvdoc** [comment]
@nicholst could you please let us know if it's clear enough now? thanks a lot!

**Comment by nicholst** [comment]
Yes!  All good!  Sorry for the delay.

**Comment by mvdoc** [comment]
Thanks for your feedback! Closing this too, @pbellec.

**Comment by lunebellec** [comment]
@mvdoc thanks for addressing all the issues. We are in the process of finalizing the proceedings, I will keep you updated. In the meantime, consider the abstract accepted. Congratulations!
